import { AssetTypeEnum } from 'modules/enums/Asset.enum';
import {
  HUNNY_POOL,
  HUNNY_BNB_POOL,
  CAKE_BNB_FLIP_POOL,
  BUSD_BNB_FLIP_POOL,
  USDT_BNB_FLIP_POOL,
  CAKE_POOL,
  DOGE_BNB_FLIP_POOL,
  BANANA_POOL,
  BANANA_BNB_POOL,
  BUNNY_BNB_FLIP_POOL,
  LINK_BNB_FLIP_POOL,
  HUNNY_ACE_POOL,
  USDC_POOL,
  USDT_POOL,
  BUSD_POOL,
  BABY_POOL,
  BUSD_BNB_FLIP_LEGACY_POOL,
  CAKE_BNB_FLIP_LEGACY_POOL,
  DOGE_BNB_FLIP_LEGACY_POOL,
  USDT_BNB_FLIP_LEGACY_POOL,
  BNB_POOL,
  HUNNY_AUTO_POOL,
  BUSD_ALPACA_POOL,
  BTCB_ALPACA_POOL,
  ETH_ALPACA_POOL,
  USDT_ALPACA_POOL,
  TUSD_ALPACA_POOL,
  ALPACA_POOL,
  FIL_ALPACA_POOL,
  CAKE_LOVE_POOL,
} from '../../constants/pools';
import { CACHE_KEY, getCachedData } from '../../modules/cacheData';
import { PoolsState } from '../../modules/models/pool.model';

export const initialPoolState: PoolsState = {
  selectedPoolType: 'BSC',

  totalDepositedValue: null,
  isAPIfailed: false,
  totalMarketCap: getCachedData(CACHE_KEY.TOTAL_MARKET_CAP),
  antiWhaleLimit: null,

  selectedAssets: {
    [AssetTypeEnum.Asset]: {},
    [AssetTypeEnum.Farm]: {},
    [AssetTypeEnum.Status]: {},
  },
  searchValue: '',

  pools: {
    BSC: [
      CAKE_LOVE_POOL,
      HUNNY_AUTO_POOL,
      HUNNY_POOL,
      HUNNY_BNB_POOL,
      CAKE_POOL,
      CAKE_BNB_FLIP_POOL,
      BANANA_POOL,
      BANANA_BNB_POOL,
      BUSD_BNB_FLIP_POOL,
      DOGE_BNB_FLIP_POOL,
      USDT_BNB_FLIP_POOL,
      BUNNY_BNB_FLIP_POOL,
      LINK_BNB_FLIP_POOL,
      HUNNY_ACE_POOL,
      USDC_POOL,
      USDT_POOL,
      BUSD_POOL,
      BNB_POOL,
      BABY_POOL,
      BUSD_ALPACA_POOL,
      USDT_ALPACA_POOL,
      BTCB_ALPACA_POOL,
      ETH_ALPACA_POOL,
      FIL_ALPACA_POOL,
      // TODO: open later
      // ALPACA_POOL,
      TUSD_ALPACA_POOL,

      CAKE_BNB_FLIP_LEGACY_POOL,
      BUSD_BNB_FLIP_LEGACY_POOL,
      USDT_BNB_FLIP_LEGACY_POOL,
      DOGE_BNB_FLIP_LEGACY_POOL,
    ],
    ETH: [],
  },

  activePoolIds: {
    BSC: [
      BNB_POOL.id,
      BABY_POOL.id,

      // TODO: open later
      // ALPACA_POOL.id,
      BUSD_ALPACA_POOL.id,
      USDT_ALPACA_POOL.id,

      BANANA_POOL.id,
      BANANA_BNB_POOL.id,
      USDC_POOL.id,
      USDT_POOL.id,
      BUSD_POOL.id,
    ],
    ETH: [],
  },
  depositedPoolIds: {
    BSC: [],
    ETH: [],
  },
  unsupportedPoolIds: {
    BSC: [
      CAKE_LOVE_POOL.id,
      HUNNY_AUTO_POOL.id,
      HUNNY_ACE_POOL.id,
      HUNNY_BNB_POOL.id,
      BTCB_ALPACA_POOL.id,
      ETH_ALPACA_POOL.id,
      CAKE_POOL.id,
      CAKE_BNB_FLIP_POOL.id,
      HUNNY_POOL.id,
      BUSD_BNB_FLIP_POOL.id,
      USDT_BNB_FLIP_POOL.id,
      LINK_BNB_FLIP_POOL.id,
      DOGE_BNB_FLIP_POOL.id,
      BUNNY_BNB_FLIP_POOL.id,
      FIL_ALPACA_POOL.id,
      TUSD_ALPACA_POOL.id,
      CAKE_BNB_FLIP_LEGACY_POOL.id,
      BUSD_BNB_FLIP_LEGACY_POOL.id,
      USDT_BNB_FLIP_LEGACY_POOL.id,
      DOGE_BNB_FLIP_LEGACY_POOL.id,
    ],
    ETH: [],
  },
};
